### ISSUE TITLE
Use f strings instead of old style format

### ISSUE THREAD

**Issue by ottobackwards** [palindromicity/dotifi#72]
Need to update to better python

**Comment by jbx09** [comment]
Hi @ottobackwards , I am new to Github contributions, but I have good experience in Python. Let me know If I can help in closing this issue. It would be of great help if you could point me towards right direction. Thanks.

**Comment by ottobackwards** [comment]
check out https://github.com/palindromicity/dotifi/blob/main/CONTRIBUTING.md

**Comment by jbx09** [comment]
Thanks, will take this issue up and update.

**Comment by ottobackwards** [comment]
ok, 
I don't know if anyone else has tried the contributor guide, so if you have issues, you can post them.
there is a slack you can join as well -> palindromicity.slack.com

**Comment by jbx09** [comment]
ok Thanks, I will validate the steps and see.
